### ISSUE TITLE
数字不能映射回去

### ISSUE THREAD

**Issue by Finsenty54** [FantasticLBP/Anti-WebSpider#2]
Util下没有analysis和map
//根据当前时间返回字体文件
    if (pathname.indexOf("analysis") > -1)
这段代码不是很懂

**Comment by Finsenty54** [comment]
傻了，CROS，我说为什么不能访问文件，把localhost改成127.0.0.1就好了，这就同源了

**Comment by FantasticLBP** [comment]
不可以滥用 issue 机制。这明显是你代码没读懂。
