### ISSUE TITLE
这种unicode进行反爬虫，会不会影响seo

### ISSUE THREAD

**Issue by MuseMatrix** [FantasticLBP/Anti-WebSpider#3]

**Comment by FantasticLBP** [comment]
SEO 一般针对文字或者 meta 信息。如果在我的这个反扒策略下做 SEO 可以给文档增加自定义属性或者 title 等。比如 <label data-seo = "价格： 298元">价格： 381元</label> 298是真实数据，381 是反扒处理后的文字。
